apiVersion: apps/v1
kind: Deployment
metadata:
    name: echo-app
spec:
    selector:
        matchLabels:
            app: echo-app
    replicas: 2
    template:
        metadata:
            labels:
                app: echo-app
        spec:
            containers:
                - name: echo-app
                  image: keke65/breizhsport-front:develop
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: echo-svc
spec:
    ports:
        - port: 80
          targetPort: 3000
    selector:
        app: echo-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-echo
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: 'false'
        nginx.ingress.kubernetes.io/use-regex: 'true'
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - http:
              paths:
                  - path: /(.*)
                    pathType: ImplementationSpecific
                    backend:
                        service:
                            name: echo-svc
                            port:
                                number: 80
