name: CI/CD Main

on:
    push:
        branches:
            - main
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]'

jobs:
    get-tag:
        runs-on: ubuntu-latest
        outputs:
            tag: ${{steps.get-tag-version.outputs.tag}}
        steps:
            - name: Set output
              id: get-tag-version
              run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    unit_and_integration_tests:
        strategy:
            matrix:
                node-version: [22.x]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.unit-integration.yml@develop
        with:
            node-version: ${{ matrix.node-version }}
    e2e_tests:
        strategy:
            matrix:
                node-version: [22.x]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.e2e.yml@develop
        with:
            node-version: ${{ matrix.node-version }}
    publish_to_docker:
        needs: [unit_and_integration_tests, e2e_tests, get-tag]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/publish.docker.yml@develop
        secrets:
            tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-front:${{needs.get-tag.outputs.tag}}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
