# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - '!main'
      - '!develop'
  pull_request:
    branches:
      - '!main'
      - '!develop'

jobs:
  unit_and_integration_tests:
    strategy:
      matrix:
        node-version: [22.x]
    uses: Kevin-Moreau65/breizhsport-front/.github/workflows/test.unit-integration.yml@develop
    with:
      node-version: ${{ matrix.node-version }}
  e2e_tests:
    strategy:
      matrix:
        node-version: [22.x]
    uses: Kevin-Moreau65/breizhsport-front/.github/workflows/test.e2e.yml@develop
    with:
      node-version: ${{ matrix.node-version }}
  publish_to_docker:
    needs: [unit_and_integration_tests, e2e_tests]
    uses: Kevin-Moreau65/breizhsport-front/.github/workflows/publish.docker.yml@develop
    secrets:
      tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-front:${{ github.head_ref || github.ref_name }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
