name: CI/CD Dev

on:
    push:
        branches:
            - develop
    pull_request:
        branches:
            - develop
        types:
            - opened
            - edited
permissions:
    id-token: write
    contents: read
jobs:
    unit_and_integration_tests:
        strategy:
            matrix:
                node-version: [22.x]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.unit-integration.yml@develop
        with:
            node-version: ${{ matrix.node-version }}
    e2e_tests:
        strategy:
            matrix:
                node-version: [22.x]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.e2e.yml@develop
        with:
            node-version: ${{ matrix.node-version }}
    quality_tests:
        needs: [unit_and_integration_tests, e2e_tests]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.quality.yml@develop
        secrets:
            SONAR_CLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
            coverage_folder: ./coverage
            coverage_artifact_name: coverage
    publish_to_docker:
        needs: [unit_and_integration_tests, e2e_tests, quality_tests]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/publish.docker.yml@develop
        secrets:
            tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-front:${{github.event_name == 'pull_request' && format('develop-pr-{0}', github.event.number) || 'develop'}}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
    pentest:
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.pentest.yml@develop
        secrets:
            AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
            AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
            AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        with:
            tag: develop-pr-${{github.event.number}}
        if: github.event_name == 'pull_request'
