name: CI/CD Main

on:
    pull_request:
        branches:
            - 'release/**'

jobs:
    unit_and_integration_tests:
        strategy:
            matrix:
                node-version: [22.x]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.unit-integration.yml@develop
        with:
            node-version: ${{ matrix.node-version }}
    e2e_tests:
        strategy:
            matrix:
                node-version: [22.x]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.e2e.yml@develop
        with:
            node-version: ${{ matrix.node-version }}
    pentest:
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.pentest.yml@develop
        secrets:
            AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
            AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
            AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
    publish_to_docker:
        needs: [unit_and_integration_tests, e2e_tests]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/publish.docker.yml@develop
        secrets:
            tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-front:release-${{ github.event.pull_request.title }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
