name: Remove Docker image from release PR

on:
    pull_request:
        branches:
            - 'release/**'
        types:
            - closed

jobs:
    remove_docker_image_pr:
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/docker-hub.remove-tag.yml@develop
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        with:
            image: breizhsport-front
            tag: reelase-pr-${{github.event.pull_request.title}}
