# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD Branches

on:
    push:
        branches:
            - '*'
            - '*/*'
            - '**'
            - '!main'
            - '!develop'
    pull_request:
        branches:
            - '*'
            - '*/*'
            - '**'
            - '!main'
            - '!develop'

jobs:
    unit_and_integration_tests:
        strategy:
            matrix:
                node-version: [22.x]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.unit-integration.yml@develop
        with:
            node-version: ${{ matrix.node-version }}
    e2e_tests:
        strategy:
            matrix:
                node-version: [22.x]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/test.e2e.yml@develop
        with:
            node-version: ${{ matrix.node-version }}
    extract_branch_name:
        needs: [unit_and_integration_tests, e2e_tests]
        runs-on: ubuntu-latest
        outputs:
            branch: ${{ steps.extract_branch.outputs.branch }}
        steps:
            - name: get branch name
              shell: bash
              id: extract_branch
              run: |
                  BRANCH_NAME=$(echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | grep -oP "\/.+" | cut -c2-)
                  echo "branch=${BRANCH_NAME}" >> $GITHUB_OUTPUT
    publish_to_docker_push_event:
        needs: [extract_branch_name]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/publish.docker.yml@develop
        secrets:
            tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-front:${{needs.extract_branch_name.outputs.branch}}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        if: github.event_name != 'pull_request'
    publish_to_docker_pr_event:
        needs: [extract_branch_name]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/publish.docker.yml@develop
        secrets:
            tags: ${{ secrets.DOCKER_USERNAME }}/breizhsport-front:${{needs.extract_branch_name.outputs.branch}}-pr-${{ github.event.number }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        if: github.event_name == 'pull_request'
