name: Test

on:
    push:
        branches:
            - develop
permissions:
    id-token: write
    contents: read
jobs:
    create_resource_group:
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/azure.resource-group.create.yml@develop
        secrets:
            AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
            AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
            AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        with:
            resource_group_name: ${{github.sha}}
    create_aks:
        needs: [create_resource_group]
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/azure.aks.create.yml@develop
        secrets:
            AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
            AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
            AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        with:
            resource_group_name: ${{github.sha}}
            aks_resource_group_name: ${{github.sha}}-aks
            aks_name: pentest-aks
    deploy_on_aks:
        needs: [create_aks]
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - uses: actions/checkout@v4
            - name: Azure login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Setup Helm
              uses: azure/setup-helm@v4.2.0
            - name: Install ingress nginx
              run: |
                  helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
                  helm repo update
                  helm install nginx-ingress ingress-nginx/ingress-nginx --namespace nginx --create-namespace
            - name: Deploy front app
              uses: azure/cli@v2
              with:
                  inlineScript: |
                      kubectl apply -f test.yaml -n nginx
            - name: Sleep for 30 seconds
              run: sleep 30s
              shell: bash
            - name: Get public IP Adress
              uses: azure/cli@v2
              id: ipAddress
              with:
                  azcliversion: latest
                  inlineScript: |
                      IP=$(az network public-ip list -g breizhsport-poc-AKS | jq -r '.[0].ipAddress')
                      echo "IPADDRESS=$IP" >> $GITHUB_OUTPUT
            - name: ZAP Scan
              uses: zaproxy/action-baseline@v0.14.0
              with:
                  target: 'http://${{steps.ipAddress.outputs.IPADDRESS}}'
    remove_resource_group:
        needs: [create_resource_group, create_aks, deploy_on_aks]
        if: always()
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/azure.resource-group.delete.yml@develop
        secrets:
            AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
            AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
            AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        with:
            resource_group_name: ${{github.sha}}
    remove_aks_resource_group:
        needs: [create_resource_group, create_aks, deploy_on_aks]
        if: always()
        uses: Breizhsport-cesi-pau/breizhsport-front/.github/workflows/azure.resource-group.delete.yml@develop
        secrets:
            AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
            AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
            AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
        with:
            resource_group_name: ${{github.sha}}-aks
